import { PrismaClient, OpportunityCategory } from '@prisma/client'
import crypto from 'crypto'

const prisma = new PrismaClient()

/**
 * Compute a SHA‑256 checksum from the lower‑cased name, normalised URL host and organisation.
 */
function computeChecksum(name: string, url: string, org: string): string {
  let host: string
  try {
    const u = new URL(url)
    host = u.origin
  } catch {
    host = url.toLowerCase()
  }
  const data = name.toLowerCase() + host + org.toLowerCase()
  return crypto.createHash('sha256').update(data).digest('hex')
}

async function main() {
  const now = new Date()
  const sample: Array<{
    name: string
    category: OpportunityCategory
    disciplines: string[]
    location: string
    org: string
    amount?: number
    currency?: string
    opensOn?: Date
    closesOn?: Date
    url: string
    eligibility: string[]
    fee?: number
    source: string
    tags: string[]
  }> = [
    {
      name: 'Emerging Artist Grant',
      category: OpportunityCategory.Grant,
      disciplines: ['Painting', 'Drawing'],
      location: 'NSW, Australia',
      org: 'ArtStart Foundation',
      amount: 5000,
      currency: 'AUD',
      opensOn: new Date('2025-01-01'),
      closesOn: new Date('2025-02-15'),
      url: 'https://example.org/emerging-artist-grant',
      eligibility: ['Emerging artists residing in NSW'],
      fee: 0,
      source: 'seed',
      tags: ['emerging', 'grant'],
    },
    {
      name: 'Public Art EOI: City Plaza',
      category: OpportunityCategory.EOI,
      disciplines: ['Public Art', 'Sculpture'],
      location: 'Sydney, Australia',
      org: 'City of Example',
      amount: 50000,
      currency: 'AUD',
      opensOn: new Date('2025-08-10'),
      closesOn: new Date('2025-09-15'),
      url: 'https://example.gov/arts/public-art-eoi',
      eligibility: ['Australian citizens/residents', 'Public art experience'],
      fee: 0,
      source: 'seed',
      tags: ['public art', 'eoi'],
    },
    {
      name: 'International Residency – Tokyo',
      category: OpportunityCategory.Residency,
      disciplines: ['Animation', 'Film', 'Digital'],
      location: 'Tokyo, Japan',
      org: 'Tokyo Arts Council',
      amount: 10000,
      currency: 'AUD',
      opensOn: new Date('2025-03-01'),
      closesOn: new Date('2025-04-30'),
      url: 'https://tokyoarts.jp/residency',
      eligibility: ['Artists 18+'],
      fee: 50,
      source: 'seed',
      tags: ['residency', 'international'],
    },
    {
      name: 'Digital Storytelling Grant',
      category: OpportunityCategory.Grant,
      disciplines: ['Film', 'Digital', 'Animation'],
      location: 'Australia',
      org: 'Digital Futures Fund',
      amount: 15000,
      currency: 'AUD',
      opensOn: new Date('2025-05-01'),
      closesOn: new Date('2025-05-31'),
      url: 'https://digitalfutures.org/grants/storytelling',
      eligibility: ['Australian citizens', 'Emerging and mid‑career'],
      fee: 0,
      source: 'seed',
      tags: ['digital', 'film'],
    },
    {
      name: 'Regional Mural Commission',
      category: OpportunityCategory.EOI,
      disciplines: ['Murals', 'Public Art'],
      location: 'Regional NSW, Australia',
      org: 'Regional Arts NSW',
      amount: 8000,
      currency: 'AUD',
      opensOn: new Date('2025-06-01'),
      closesOn: new Date('2025-07-15'),
      url: 'https://regionalartsnsw.org.au/mural-eoi',
      eligibility: ['NSW residents', 'Experience painting large‑scale works'],
      fee: 0,
      source: 'seed',
      tags: ['mural', 'regional'],
    },
    {
      name: 'Young Filmmaker Award',
      category: OpportunityCategory.Award,
      disciplines: ['Film'],
      location: 'Australia',
      org: 'National Film Institute',
      amount: 25000,
      currency: 'AUD',
      opensOn: new Date('2025-02-01'),
      closesOn: new Date('2025-03-31'),
      url: 'https://nfi.gov.au/awards/young-filmmaker',
      eligibility: ['Under 30', 'Australian citizens'],
      fee: 25,
      source: 'seed',
      tags: ['award', 'film', 'youth'],
    },
    {
      name: 'Interactive Art Residency',
      category: OpportunityCategory.Residency,
      disciplines: ['Interactive', 'AR/VR', 'Digital'],
      location: 'Melbourne, Australia',
      org: 'Melbourne Media Lab',
      amount: 12000,
      currency: 'AUD',
      opensOn: new Date('2025-09-01'),
      closesOn: new Date('2025-10-10'),
      url: 'https://medialab.com/residency',
      eligibility: ['Australian citizens', 'Experience in AR/VR'],
      fee: 0,
      source: 'seed',
      tags: ['residency', 'digital', 'ar/vr'],
    },
    {
      name: 'Community Co‑design Project Grant',
      category: OpportunityCategory.Grant,
      disciplines: ['Public Art', 'Community'],
      location: 'Brisbane, Australia',
      org: 'Brisbane City Council',
      amount: 7000,
      currency: 'AUD',
      opensOn: new Date('2025-04-01'),
      closesOn: new Date('2025-05-15'),
      url: 'https://brisbane.qld.gov.au/community-grants',
      eligibility: ['Queensland residents', 'Community engagement experience'],
      fee: 0,
      source: 'seed',
      tags: ['grant', 'community', 'public art'],
    },
    {
      name: 'Game Development Residency',
      category: OpportunityCategory.Residency,
      disciplines: ['Game', 'Digital'],
      location: 'Adelaide, Australia',
      org: 'GameLab SA',
      amount: 15000,
      currency: 'AUD',
      opensOn: new Date('2025-05-01'),
      closesOn: new Date('2025-06-15'),
      url: 'https://gamelabsa.com/residency',
      eligibility: ['Australian citizens', 'Experience in game development'],
      fee: 0,
      source: 'seed',
      tags: ['game', 'residency'],
    },
    {
      name: 'International Mural Exchange',
      category: OpportunityCategory.Residency,
      disciplines: ['Murals'],
      location: 'Berlin, Germany',
      org: 'Berlin Arts Exchange',
      amount: 5000,
      currency: 'EUR',
      opensOn: new Date('2025-07-01'),
      closesOn: new Date('2025-08-30'),
      url: 'https://berlinartsexchange.de/mural',
      eligibility: ['Open to all'],
      fee: 0,
      source: 'seed',
      tags: ['mural', 'international'],
    },
    {
      name: 'Mid‑career Artist Fellowship',
      category: OpportunityCategory.Grant,
      disciplines: ['Painting', 'Sculpture'],
      location: 'Australia',
      org: 'Arts Council Australia',
      amount: 30000,
      currency: 'AUD',
      opensOn: new Date('2025-06-01'),
      closesOn: new Date('2025-07-31'),
      url: 'https://artscouncil.gov.au/fellowship',
      eligibility: ['Mid‑career artists'],
      fee: 0,
      source: 'seed',
      tags: ['grant', 'mid‑career'],
    },
    // Additional sample records to reach ~20 entries
    {
      name: 'Digital Media Residency – New York',
      category: OpportunityCategory.Residency,
      disciplines: ['Digital', 'Film'],
      location: 'New York, USA',
      org: 'NYC Media Arts',
      amount: 20000,
      currency: 'USD',
      opensOn: new Date('2025-02-01'),
      closesOn: new Date('2025-03-10'),
      url: 'https://nycmediaarts.org/residency',
      eligibility: ['International artists'],
      fee: 100,
      source: 'seed',
      tags: ['digital', 'residency'],
    },
    {
      name: 'Urban Sculpture Award',
      category: OpportunityCategory.Award,
      disciplines: ['Sculpture', 'Public Art'],
      location: 'Perth, Australia',
      org: 'Western Arts Board',
      amount: 10000,
      currency: 'AUD',
      opensOn: new Date('2025-04-01'),
      closesOn: new Date('2025-06-30'),
      url: 'https://waarts.gov.au/urban-sculpture',
      eligibility: ['Australian citizens'],
      fee: 20,
      source: 'seed',
      tags: ['award', 'sculpture'],
    },
    {
      name: 'AR/VR Innovation Grant',
      category: OpportunityCategory.Grant,
      disciplines: ['AR/VR', 'Digital'],
      location: 'Worldwide',
      org: 'TechArts Foundation',
      amount: 100000,
      currency: 'USD',
      opensOn: new Date('2025-01-15'),
      closesOn: new Date('2025-03-15'),
      url: 'https://techarts.org/innovation-grant',
      eligibility: ['Open to all', 'AR/VR projects'],
      fee: 0,
      source: 'seed',
      tags: ['digital', 'ar/vr', 'grant'],
    },
    {
      name: 'Experimental Sound Residency',
      category: OpportunityCategory.Residency,
      disciplines: ['Music', 'Digital'],
      location: 'Paris, France',
      org: 'Paris Sound Lab',
      amount: 7000,
      currency: 'EUR',
      opensOn: new Date('2025-03-20'),
      closesOn: new Date('2025-05-20'),
      url: 'https://parissoundlab.fr/residency',
      eligibility: ['Musicians interested in experimental sound'],
      fee: 0,
      source: 'seed',
      tags: ['residency', 'music'],
    },
    {
      name: 'Environmental Art Grant',
      category: OpportunityCategory.Grant,
      disciplines: ['Public Art', 'Installation'],
      location: 'Canberra, Australia',
      org: 'Green Arts Initiative',
      amount: 12000,
      currency: 'AUD',
      opensOn: new Date('2025-05-10'),
      closesOn: new Date('2025-07-01'),
      url: 'https://greenarts.org.au/environmental-grant',
      eligibility: ['Projects focused on sustainability'],
      fee: 0,
      source: 'seed',
      tags: ['grant', 'environment', 'installation'],
    },
    {
      name: 'Street Art Award',
      category: OpportunityCategory.Award,
      disciplines: ['Street Art', 'Murals'],
      location: 'Sydney, Australia',
      org: 'Street Arts Festival',
      amount: 5000,
      currency: 'AUD',
      opensOn: new Date('2025-09-01'),
      closesOn: new Date('2025-11-15'),
      url: 'https://streetartsfest.com/award',
      eligibility: ['Artists based in Australia'],
      fee: 10,
      source: 'seed',
      tags: ['award', 'street art'],
    },
    {
      name: 'Cultural Exchange Residency',
      category: OpportunityCategory.Residency,
      disciplines: ['Performance', 'Music'],
      location: 'Havana, Cuba',
      org: 'Cultural Exchange Program',
      amount: 8000,
      currency: 'USD',
      opensOn: new Date('2025-02-15'),
      closesOn: new Date('2025-04-01'),
      url: 'https://culturexchange.org/residency',
      eligibility: ['Artists interested in cross‑cultural collaboration'],
      fee: 0,
      source: 'seed',
      tags: ['residency', 'international', 'music'],
    },
    {
      name: 'Innovation in Games Grant',
      category: OpportunityCategory.Grant,
      disciplines: ['Game'],
      location: 'Worldwide',
      org: 'Global Game Fund',
      amount: 20000,
      currency: 'USD',
      opensOn: new Date('2025-01-20'),
      closesOn: new Date('2025-02-28'),
      url: 'https://globalgamefund.org/innovation-grant',
      eligibility: ['Indie game developers'],
      fee: 0,
      source: 'seed',
      tags: ['game', 'grant'],
    },
    {
      name: 'Artist Exchange Residency – Seoul',
      category: OpportunityCategory.Residency,
      disciplines: ['Digital', 'Installation'],
      location: 'Seoul, South Korea',
      org: 'Seoul Art Center',
      amount: 9000,
      currency: 'USD',
      opensOn: new Date('2025-07-15'),
      closesOn: new Date('2025-09-01'),
      url: 'https://seoularcenter.kr/residency',
      eligibility: ['International artists'],
      fee: 0,
      source: 'seed',
      tags: ['residency', 'international', 'installation'],
    },
    {
      name: 'Film Festival Submission Grant',
      category: OpportunityCategory.Grant,
      disciplines: ['Film'],
      location: 'Australia',
      org: 'Australian Film Fund',
      amount: 5000,
      currency: 'AUD',
      opensOn: new Date('2025-05-01'),
      closesOn: new Date('2025-06-15'),
      url: 'https://filmfund.au/grants/festival-submission',
      eligibility: ['Australian filmmakers'],
      fee: 0,
      source: 'seed',
      tags: ['film', 'grant'],
    },
    {
      name: 'Mid‑career Digital Artist Award',
      category: OpportunityCategory.Award,
      disciplines: ['Digital'],
      location: 'Australia',
      org: 'Digital Arts Council',
      amount: 10000,
      currency: 'AUD',
      opensOn: new Date('2025-08-01'),
      closesOn: new Date('2025-09-30'),
      url: 'https://digitalartscouncil.org/award/mid-career',
      eligibility: ['Mid‑career digital artists'],
      fee: 0,
      source: 'seed',
      tags: ['digital', 'award', 'mid‑career'],
    },
    {
      name: 'AR/VR Residency – Los Angeles',
      category: OpportunityCategory.Residency,
      disciplines: ['AR/VR', 'Interactive'],
      location: 'Los Angeles, USA',
      org: 'Immersive Arts Hub',
      amount: 15000,
      currency: 'USD',
      opensOn: new Date('2025-03-15'),
      closesOn: new Date('2025-05-01'),
      url: 'https://immersiveartshub.com/residency',
      eligibility: ['Experience with AR/VR'],
      fee: 0,
      source: 'seed',
      tags: ['residency', 'ar/vr'],
    },
    {
      name: 'Community Arts Fellowship',
      category: OpportunityCategory.Grant,
      disciplines: ['Community', 'Public Art'],
      location: 'NSW, Australia',
      org: 'Community Arts NSW',
      amount: 6000,
      currency: 'AUD',
      opensOn: new Date('2025-04-15'),
      closesOn: new Date('2025-06-01'),
      url: 'https://communityartsnsw.org/fellowship',
      eligibility: ['NSW residents'],
      fee: 0,
      source: 'seed',
      tags: ['fellowship', 'community'],
    },
    {
      name: 'Interactive Performance Residency',
      category: OpportunityCategory.Residency,
      disciplines: ['Performance', 'Interactive'],
      location: 'London, UK',
      org: 'Interactive Theatre Lab',
      amount: 8000,
      currency: 'GBP',
      opensOn: new Date('2025-09-01'),
      closesOn: new Date('2025-10-15'),
      url: 'https://theatrelab.co.uk/residency',
      eligibility: ['Performing artists with interactive works'],
      fee: 0,
      source: 'seed',
      tags: ['residency', 'interactive', 'performance'],
    },
    {
      name: 'Design for Social Impact Grant',
      category: OpportunityCategory.Grant,
      disciplines: ['Design', 'Social Impact'],
      location: 'Worldwide',
      org: 'Design Impact Fund',
      amount: 25000,
      currency: 'USD',
      opensOn: new Date('2025-02-01'),
      closesOn: new Date('2025-04-01'),
      url: 'https://designimpactfund.org/grant',
      eligibility: ['Open to all disciplines'],
      fee: 0,
      source: 'seed',
      tags: ['design', 'social impact', 'grant'],
    },
  ]

  // Convert to DB format, compute checksums and lastCheckedAt
  const data = sample.map(op => {
    return {
      ...op,
      checksum: computeChecksum(op.name, op.url, op.org),
      lastCheckedAt: now,
      createdAt: now,
      updatedAt: now,
    }
  })

  // Clear existing records and insert new ones
  await prisma.savedItem.deleteMany()
  await prisma.opportunity.deleteMany()
  await prisma.opportunity.createMany({ data })
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })